Add VM File handling to qcore
ucgmsim/qcore pull request #212
Opened 2021-02-11 02:43 UTC by jpa198

Create simulation structure functions for Qp/Qs files and vm_params

2021-02-11 03:15 UTC, jasonmotha requested changes

2021-02-11 03:15 UTC, jasonmotha commented on qcore/vm_file.py
> +    def __init__(self, nx, ny, nz, file_loc=None):
Default should have a read_only attribute

2021-02-11 03:15 UTC, jasonmotha commented on qcore/vm_file.py
> +            self._data = np.swapaxes(self._data, 0, 2)
Either abstract the swapping axeses away or explain what's happening here.

2021-02-11 03:15 UTC, jasonmotha commented on qcore/vm_file.py
> +    def set_value(self, value, x, y, z):
doc string. About changing data but not writing to file.

2021-02-12 03:21 UTC, jpa198 commented on qcore/vm_file.py
> +        vmf.set_values(np.ones(vmf.shape)*value)
TIL

2021-02-12 03:30 UTC, jasonmotha approved these changes

2021-02-18 03:21 UTC, jasonmotha approved these changes

2021-02-18 03:27 UTC, jpa198 commented
Even without the Qp/Qs stuff, I feel this is ready to go into the repo

2021-02-18 03:28 UTC, jasonmotha commented
Agreed.

2021-02-18 03:42 UTC, shot0829 approved these changes

2021-02-18 03:45 UTC, merged