Custom filename
ucgmsim/qcore pull request #302
Opened 2024-05-09 23:23 UTC by joelridden

Allows a custom filename for writing a text file
Utilized by the NZGMDB for ensuring the outputs are not overwritten since Station.Comp can be common for multiple records

2024-05-10 01:30 UTC, sungeunbae requested changes

2024-05-10 01:30 UTC, sungeunbae commented on qcore/timeseries.py
> +    txt = open(filename, "wb")
let's write the file inside "with".

2024-05-10 01:40 UTC, sungeunbae approved these changes

2024-05-13 04:09 UTC, lispandfound approved these changes

2024-05-13 04:09 UTC, lispandfound commented on qcore/timeseries.py
> +                % (nt, dt, start_hr, start_min, start_sec, edist, az, baz)
I know you didn't write this format specifier, but we should migrate this to a proper f-string considering the last time this syntax was state-of-the-art I was still in high school.

2024-05-13 04:47 UTC, AndrewRidden-Harper approved these changes

2024-05-13 20:25 UTC, claudio525 approved these changes

2024-05-13 22:34 UTC, merged