Extract data download
ucgmsim/qcore pull request #320
Opened 2024-07-11 00:48 UTC by joelridden

2024-07-11 03:37 UTC, claudio525 approved these changes

2024-07-11 03:52 UTC, AndrewRidden-Harper submitted a review, later dismissed
looks good

2024-07-11 22:30 UTC, lispandfound commented on download_data.py
> +NO_DATA_ARG = "--no-data"
We can drop the `NO_DATA_ARG` variable now.

2024-07-11 22:32 UTC, lispandfound commented on download_data.py
> +def prepare_data():
```suggestion
def download_data():
```

2024-07-11 22:33 UTC, lispandfound commented on download_data.py
> +prepare_data()
I would change this to 

```python
if __name__ == '__main__':
    download_data()
```

That way, if I import the module the data would not download until I call `download_data()`

2024-07-11 22:34 UTC, lispandfound requested changes
I would like to be able to call the function in this script from another module. I would propose moving this into `qcore/data.py` and then that way I can write code that does 

```python
from qcore import data

data.prepare_data()
```

To download the data in scripts that require it.

2024-07-11 23:24 UTC, lispandfound approved these changes

2024-07-14 20:27 UTC, claudio525 approved these changes

2024-07-14 22:19 UTC, sungeunbae approved these changes

2024-07-15 22:08 UTC, AndrewRidden-Harper submitted a review, later dismissed

2024-07-15 22:49 UTC, lispandfound requested changes
In my own testing of this PR it doesn't quite work as expected. If you call the script with your current working directory anywhere but `qcore/data/` it will fail. To remedy this, I made the following change to the download_data.py script to make things work how it should:

```python
# from pathlib import Path
# import tempfile
# from urllib import request
def download_data():
    download_location = Path(__file__).parent
    loc_version = download_location / "version"

    have_ver = get_version(loc_version)
    if str(have_ver) != DATA_VERSION:
        print("data package missing or incorrect version")
        print("downloading...")
        with tempfile.NamedTemporaryFile() as data_archive_file:
            request.urlretrieve(DATA_URL, data_archive_file.name)
            extract_data(data_archive_file.name, download_location.parent)
    # final check
    have_ver = get_version(loc_version)
    if str(have_ver) != DATA_VERSION:
        sys.exit("data package issue, please contact repository maintainer")
```

Note that the download location is sourced from `__file__`. This approach will not work if you invoke the script from the command line, however. So @joelridden will need to find a different work around to work with both the CLI and the import-and-download methods.

2024-07-15 23:06 UTC, lispandfound commented
Also just something to think about, but the GitHub release download host is horrifically slow (like 2Mb/s vs Dropbox at 52Mb/s). Perhaps there is a better place to host nearly 2gb of data than a GitHub release link?

2024-07-15 23:17 UTC, sungeunbae commented
> Also just something to think about, but the GitHub release download host is horrifically slow (like 2Mb/s vs Dropbox at 52Mb/s). Perhaps there is a better place to host nearly 2gb of data than a GitHub release link?

Dropbox will do. Just remember this bit!
![image](https://github.com/user-attachments/assets/c1532cc8-6b65-4944-af7d-7a16c348f857)

2024-07-15 23:44 UTC, lispandfound commented
Link here: https://www.dropbox.com/scl/fi/p5so9irbx43c9g96jr2qr/qcore_resources.tar.xz?rlkey=pgmn69e212c0zx0fauxuikgky&dl=0

2024-07-30 02:01 UTC, claudio525 approved these changes

2024-07-30 04:03 UTC, lispandfound approved these changes

2024-07-30 21:39 UTC, sungeunbae approved these changes

2024-07-31 00:57 UTC, AndrewRidden-Harper approved these changes

2024-07-31 00:57 UTC, merged