Source to site calculation moved from IM_calculation repo
ucgmsim/qcore pull request #323
Opened 2024-08-02 05:02 UTC by sungeunbae

See https://github.com/ucgmsim/IM_calculation/pull/170

A PR from Empirical engine depends on this PR: https://github.com/ucgmsim/Empirical_Engine/pull/113

I am not entirely sure what to do with calculate_rrups_single.py - I think it is no longer needed to exist as a separate script.
Your feedback is welcome :)

2024-08-04 19:44 UTC, claudio525 commented on qcore/source_site_dist/calculate_rrups_single.py
If we are not using it, then remove it I recon

2024-08-04 21:44 UTC, sungeunbae commented on qcore/source_site_dist/calculate_rrups_single.py
Removed it

2024-08-04 22:05 UTC, joelridden commented on qcore/test/test_source_site_dist/test_src_site_dist_calc.py
> +def test_calc_rrub_rjb(set_up):
The issues your having from the tests stem from this set_up which was a shared function for the tests in IM_calculation which setup the testing env with input output I believe

2024-08-05 01:23 UTC, lispandfound requested changes

2024-08-05 01:23 UTC, lispandfound commented on qcore/src_site_dist.py
> +    type=2,
Missing type signatures

2024-08-05 01:23 UTC, lispandfound commented on qcore/src_site_dist.py
> +    """
These docs should be in the numpydoc format.

2024-08-05 01:23 UTC, lispandfound commented on qcore/src_site_dist.py
> +    hypocentre_origin=False,
missing type signatures.

2024-08-05 02:05 UTC, AndrewRidden-Harper commented on qcore/src_site_dist.py
> +    Calculates Rx and Ry distances using the cross track and along track distance calculations
Echoing @lispandfound 's comment, this doc is also not in numpy format

2024-08-05 02:06 UTC, AndrewRidden-Harper commented on qcore/src_site_dist.py
> +    :param srf_points: An array with shape (n, 3) giving the lon, lat, depth location of each subfault
Also not in numpy doc format

2024-08-05 02:08 UTC, AndrewRidden-Harper reviewed
looks good. A few small comments

2024-08-06 01:49 UTC, lispandfound submitted a review, later dismissed

2024-08-06 21:10 UTC, lispandfound commented on qcore/test/test_source_site_dist/test_src_site_dist_calc.py
> +            # download_via_ftp(DATA_DOWNLOAD_PATH, zip_download_path)
do we really need the commented lines here? We can always fish them out of the git history if we need them.

2024-08-06 23:25 UTC, joelridden approved these changes

2024-08-06 23:26 UTC, sungeunbae commented
@joelridden @lispandfound @AndrewRidden-Harper   I just removed the test to get this PR merged quickly. Will add the test as a separate PR, I promise!

2024-08-06 23:28 UTC, AndrewRidden-Harper approved these changes

2024-08-06 23:30 UTC, lispandfound approved these changes

2024-08-06 23:30 UTC, merged